### ISSUE TITLE
required system privacy and automation permissions are undocumented

### ISSUE THREAD

**Issue by ckundo** [ckundo/auto-vo#10]
Make sure that all of the System permissions that are required are documented in the README.

see https://github.com/ckundo/auto-vo/issues/6#issuecomment-868559391 by @sebduf

**Comment by ckundo** [comment]
@esbenem do you recall needing to set anything in System Preferences permissions on initial use?

**Comment by ckundo** [comment]
@sebduf please try enabling Automation in System Preferences > Security and Privacy > Privacy > Automation. Terminal should be listed there.

<img width="293" alt="Screen Shot 2021-06-25 at 11 28 55 AM" src="https://user-images.githubusercontent.com/108163/123448160-9c64b600-d5a8-11eb-81f4-524a5dd30c35.png">

<img width="355" alt="Screen Shot 2021-06-25 at 11 28 59 AM" src="https://user-images.githubusercontent.com/108163/123448154-9bcc1f80-d5a8-11eb-8eca-bdc5673aa187.png">

**Comment by ckundo** [comment]
another thing that might be missing is opening VoiceOver Utility and checking "Allow VoiceOver to be controlled with AppleScript".

**Comment by esbenam** [comment]
> @esbenem do you recall needing to set anything in System Preferences permissions on initial use?

Nope, didn't have to set anything besides from allowing VoiceOver to be controlled by AppleScript. Only saw the navigation issue, which could be fixed by enabling fast search.
