### ISSUE TITLE
Page closed error trying to run

### ISSUE THREAD

**Issue by JavaDevilNZ** [ckundo/auto-vo#11]
Trying to set this up and get the following error.

Is there something I'm missing here?

```
(Path)/lib/node_modules/auto-vo/node_modules/playwright/lib/server/chromium/crPage.js:341
            this._firstNonInitialNavigationCommittedReject(new Error('Page closed'));
                                                           ^

Error: Page closed
    at CRSession.<anonymous> (Path)/lib/node_modules/auto-vo/node_modules/playwright/lib/server/chromium/crPage.js:341:60)
    at Object.onceWrapper (node:events:513:28)
    at CRSession.emit (node:events:406:35)
    at (Path)/lib/node_modules/auto-vo/node_modules/playwright/lib/server/chromium/crConnection.js:177:43
```

**Comment by ckundo** [comment]
@JavaDevilNZ are you using the CLI? does the chrome browser open at all? how long does it stay open?

**Comment by ckundo** [comment]
@JavaDevilNZ you may need to install `playwright-chromium`. Try `npm i -g playwright-chromium` and run again.

**Comment by JavaDevilNZ** [comment]
@ckundo Thanks. 
Apologies for the lack of details previously, I was in a rush to get it posted.
I should have said that this is running via a Jenkins CI pipeline which is part of the issue.

The above error occurs when I'm not signed in as the configured Jenkins user.

I also added in the `playwright-chromium` install to my node installation.

There were a few other hoops to jump through to ensure this was working, like making sure that some scripts had access to system settings around accessibility.

Once I was signed in and had permissions set, I could run my jenkins job and see the browser open and run using your example.

**Comment by ckundo** [comment]
thanks @JavaDevilNZ, glad its working now.
