### ISSUE TITLE
Feature Request: To be able to get behind http authentication

### ISSUE THREAD

**Issue by mehunter3** [ckundo/auto-vo#12]
In testing auto-vo to see if it would work for me, I found that when it goes to a URL guarded by HTTP auth it just closes the chrome window. Would it be possible to add the ability to get past http auth? Maybe if there is a way to pause the auto scan of the page or to be able to add user and password attributes to the CLI? 

All of my dev and testing sites are behind HTTP auth and it would be nice to use this on those before accessibility changes are made live.

Thanks!

**Comment by ckundo** [comment]
this is possible using playwright auth and the `auto-vo` node module in your tests: https://playwright.dev/docs/auth/. this allows you to save a logged in state during your test run. that said, please use the node module import for this functionality.

**Comment by mehunter3** [comment]
Thanks!
