### ISSUE TITLE
Feature Request: CLI option to wait a set time before processing

### ISSUE THREAD

**Issue by JavaDevilNZ** [ckundo/auto-vo#13]
I currently have some Vaadin web apps which I would like to use this for.

The problem I'm facing is that the Application Server can take a few seconds to load (showing a loading spinner) before the main page is shown.

This results in output like this:

```
Loading app. Please wait...
Loading app. Please wait...
This content is announced automatically and does not need to be navigated into.
This content is announced automatically and does not need to be navigated into. group
tooltip
```

I'm certain if this is due to the load or maybe just a poorly structure page layout, but I know that I can use other tools manually to navigate and use voice over once the page is loaded.

**Comment by ckundo** [comment]
I like this idea, though I'd prefer a check for content on the page. something like `auto-vo --url https://example.com --limit 10 --await "Example Domain --timeout 10". using a time delay is less reliable.

**Comment by ckundo** [comment]
@JavaDevilNZ I updated the package to wait for `domcontentloaded` before moving the VoiceOver cursor. Please try out `v1.2.3` and reopen this if its not solved.

**Comment by JavaDevilNZ** [comment]
@ckundo This unfortunately does not solve the issue as the loading page is in itself a document which is loaded (spinner gif) waiting for the server side application to generate the main page content.

It has solved it for some though as the initial loading page is not shown, so it is an improvement.
