### ISSUE TITLE
stopVoiceover.js: execution error: Error: Error: osascript is not allowed to send keystrokes. (1002)

### ISSUE THREAD

**Issue by ckundo** [ckundo/auto-vo#16]
This error occurs when launching the script without first enabling AppleScript in VoiceOver Utility. To fix this, enable AppleScript in VoiceOver Utility, and enable Terminal.app (or iTerm etc) to use macOS accessibility APIs.

<img width="672" alt="Screen shot of system preferences Accessibility pane with Terminal.app enabled" src="https://user-images.githubusercontent.com/108163/124666375-f3596d80-de7b-11eb-809d-d9a3e53ff4b6.png">
<img width="827" alt="Screen shot of VoiceOver Utility General pane with Applescript enabled" src="https://user-images.githubusercontent.com/108163/124666388-f6ecf480-de7b-11eb-880f-0171f13de210.png">

**Comment by philsherry** [comment]
👋🏻 I’m wanting to try this for a project, but I’m stuck at this point. 

I have `[x] Allow VoiceOver…` checked, and I’m running it from VS Code, so I’ve made sure that’s been allowed to control things. 

<img width="330" alt="Screenshot 2021-08-08 at 14 18 05" src="https://user-images.githubusercontent.com/272769/128633325-c3a29182-375b-4d03-8931-0ca5c5815764.png">

Upon running, I get a Playwright window opening with the specified URL, but then it crashes. I can’t see any logs anywhere that I can add here, otherwise, I would. If there’s a debug option that provides this, let me know and I’ll run it. 

----

While I’m here, and unrelated to that bug…

How easy would it be to target specific elements? Extending your test runner example, let’s say I want to target an element from my `fixtures.json` (`desktop.bannerGrid`, in this case), and then check the contents of *just* that element. Would that be ridiculous, or possibly doable?

```js
describe(`checking ${thing}`, async () => {
  it('returns announcements', async () => {
    const options = {
      url: `${hostname}`,
      limit: 10,
      until: 'Example',
      quiet: true,
      element: desktop.bannerGrid
    };

    const announcements = await run(options);

    expect(announcements).to.include.members([
      desktop.bannerGrid.heading,
      desktop.bannerGrid.item1.button,
      desktop.bannerGrid.item1.content,
      desktop.bannerGrid.item1.heading,
      desktop.bannerGrid.item2.button,
      desktop.bannerGrid.item2.content,
      desktop.bannerGrid.item2.heading,
      desktop.bannerGrid.item3.button,
      desktop.bannerGrid.item3.content,
      desktop.bannerGrid.item3.heading,
      desktop.bannerGrid.item4.button,
      desktop.bannerGrid.item4.content,
      desktop.bannerGrid.item4.heading,
    ]);
  }).timeout(5000);
});
```

**Comment by ckundo** [comment]
@philsherry hmm, can you check both the Automation section of Security, and tell me what you see there?

**Comment by ckundo** [comment]
also, what version of Auto VO are you using? see https://github.com/ckundo/auto-vo/issues/6

**Comment by ckundo** [comment]
could also be that scripting is not enabled in VoiceOver Utility (see https://github.com/ckundo/auto-vo/issues/9)

**Comment by philsherry** [comment]
Terminal, iTerm, VS Code (+Insiders) all have System Events + Finder checked in Automation. 

<img width="310" alt="Screenshot 2021-08-08 at 18 06 11" src="https://user-images.githubusercontent.com/272769/128639762-e457a17a-a37a-49d4-9c44-f021a4df4c5d.png">

> “I have `[x] Allow VoiceOver…` checked”

<img width="357" alt="Screenshot 2021-08-08 at 18 05 28" src="https://user-images.githubusercontent.com/272769/128639747-5ac90f89-a621-498e-85d3-f9e7403aca42.png">

I’m running `auto-vo@1.4.0`

I'll read through all of the other issues here anyway, just in case.

**Comment by ckundo** [comment]
are you able to run the command from iTerm?

**Comment by ckundo** [comment]
I have this in my automation preferences. Note that VoiceOver is missing from yours. Maybe try reinstalling the plugin and see if it prompts you again for permissions.

<img width="393" alt="Screen Shot 2021-08-08 at 1 20 55 PM" src="https://user-images.githubusercontent.com/108163/128640174-b5861be2-73b3-4a42-8a7f-8faf77061e3b.png">

**Comment by philsherry** [comment]
I wasn’t earlier, but I uninstalled and reinstalled and now I can—but only in iTerm. 

<img width="309" alt="Screenshot 2021-08-08 at 18 19 55" src="https://user-images.githubusercontent.com/272769/128640184-34f4e98d-769d-4ed3-9baa-0a36b613b3a3.png">

I’m guessing Terminal and VS Code need whatever is adding VoiceOver there. How do I force that? I can force Finder and System events to appear from whichever CLI I’m using by running these:

```applescript
osascript -e 'tell application "Finder"' -e 'set _b to bounds of window of desktop' -e 'end tell'
osascript -e 'tell application "System Events"' -e 'keystroke "t" using command down' -e 'end tell'
```

But how do I force VoiceOver to appear in there?

**Comment by philsherry** [comment]
I have `bash` and `zsh` running in different environments and I’ve just realised what’s happening here: 
- Terminal, VS Code: crashes on open, VoiceOver not added in Automation. (`bash`)
- iTerm, VS Code—Insiders: works fine, VoiceOver added in Automation. (`zsh`)

Does that get you any further?

**Comment by philsherry** [comment]
I’m aware I’ve just potentially opened a box of worms, so you might want to split this out into a new issue. Feel free to tag me in for testing.
