### ISSUE TITLE
Discussion about the API

### ISSUE THREAD

**Issue by mfrachet** [ckundo/auto-vo#2]
Hello there and thank you for the amazing work you've done 🙏🏻 .

I'm passing around and wanted to ask if you had something specific in mind to improve a bit the API and eventually decouple Playwright from the module? Or is it a strong requirement that you have and that you want to stick with it?

Willing to help in any way, if needed 😊!

**Comment by ckundo** [comment]
@mfrachet thanks for the note; Playwright isn't a strict requirement, really just needed a cross browser driver. Did you have something in mind for improvements?

**Comment by ckundo** [comment]
@mfrachet if you have ideas for improvement, please feel free to open specific issues on each one. Thanks!

**Comment by ckundo** [comment]
@mfrachet FYI i split out the VoiceOver running into https://github.com/ckundo/voiceover.js, that has no playwright dependency.

**Comment by mfrachet** [comment]
This is amazing. Thank you so much, I will try to make it run as part of https://github.com/mfrachet/cypress-audit 😊
