### ISSUE TITLE
Can the Auto Vo output be scoped in any way?

### ISSUE THREAD

**Issue by lloydi** [ckundo/auto-vo#23]
A feature idea - have the ability to specify a node within which to keep VO in. Not sure if there might be any way to do this. Presumably it'd involve something like setting focus on starting element (JS?) and then reading from there. Is there conceivably a way to say when to stop?

Anyway, just an idea to throw out there in case there is a way to do it. :)

**Comment by ckundo** [comment]
hi @lloydi, thanks for the issue. you could potentially do component specific testing against a storybook or other pattern library page. you might also check out voiceover.js for more fine grained targeting.
