### ISSUE TITLE
A way to read inside content groups?

### ISSUE THREAD

**Issue by Christopher-Hayes** [ckundo/auto-vo#25]
Is there a way to get this tool to dig a little bit deeper into content groups?

Compared to my own manual VoiceOver testing, this tool seems to give me different more "high level" output. It seems like it skips over the page content and just reads out the higher level "Content - group". Is there a way to get it to read into groups?

Here's this site I'm testing: https://kamadojoe.com

And this is the output I'm seeing:

```
Welcome to macOS. VoiceOver is on. Playwright 🎭 Playwright: about:blank window web content has keyboard focus
Kamado Joe® | Ceramic Grills | Ceramic Smoker | Kamado Grill
Links menu
Headings menu
Form Controls menu
Window Spots menu
Loading more items…
No items in Window Spots menu
Content - group
Kamado Joe® | Ceramic Grills | Ceramic Smoker | Kamado Grill
In Kamado Joe® | Ceramic Grills | Ceramic Smoker | Kamado Grill KamadoJoe's Instagram feed
Session ended
```

Maybe this is how the tool is expected to behave. Was trying to see if this cool could speed up my workflow of checking what VoiceOver says for content in the page.

**Comment by ckundo** [comment]
@Christopher-Hayes thanks for the message, you can use the [VoiceOver.js](https://github.com/AccessLint/screenreaders/blob/main/packages/voiceover/README.md) standalone JS library for this kind of thing. You'd instantiate a new `VoiceOver` object and use the `startInteracting` command. let me know if there's anything missing in the docs that I can help with.

**Comment by Christopher-Hayes** [comment]
Thanks @ckundo, that does work pretty nice.

Having a little trouble with startInteracting, it seems to just stop after a few items. But, the repo test did help me get to where I was going. The somewhat hacky node code below does the job of iterating through the page printing everything out. I have it advancing in search of text that appears at the very bottom of the page.

```bash
/usr/bin/open -a /Applications/Google\ Chrome.app 'https://kamadojoe.com'; node index.js
```

```js
import { VoiceOver } from '@accesslint/voiceover';

const voiceOver = new VoiceOver({ log: true })
await voiceOver.launch()
await new Promise(resolve => setTimeout(resolve, 3000))

try {
  await voiceOver.advance({
    target: {
      text: 'Cookies'
    },
    steps: 100,
  })
} catch (e) {
  console.log(e)
} finally {
  await voiceOver.quit()
}
```

**Comment by Christopher-Hayes** [comment]
Btw, in terms of the docs. It might help to show code using the commands. It took me a couple minutes to figure out I had to do the following to use the command.

```js
import { VoiceOver, startInteracting } from 'voiceOver';

...
voiceOver.execute(startInteracting)
...
```

**Comment by ckundo** [comment]
@Christopher-Hayes thanks for your thoughts on this.

**Comment by ckundo** [comment]
@Christopher-Hayes oh, I also just realized auto-vo is working on your page, but you need to specific both the `until` and the `limit` flags.

```
% npx @accesslint/auto-vo --url https://www.kamadojoe.com/ --until Cookies --limit 100
Welcome to macOS. VoiceOver is on. Playwright 🎭 Playwright: about:blank window toolbar
Kamado Joe® | Ceramic Grills | Ceramic Smoker | Kamado Grill web content
90% loaded.
and 1 more item web dialog button
Web Spots menu
No items in Web Spots menu
Form Controls menu
Window Spots menu
Content - group
Kamado Joe® | Ceramic Grills | Ceramic Smoker | Kamado Grill web content
In Kamado Joe® | Ceramic Grills | Ceramic Smoker | Kamado Grill web content KamadoJoe's Instagram feed frame
button
SHOP OUR FATHER'S DAY DEALS
6/3 - 6/11
FREE Cover, Charcoal & Fire Starter with a Series II or III Grill Purchase button
30% Off Charcoal Baskets button
FREE Probe Pack with the Purchase of an iKamand button
*Offers valid only for in-stock items while supplies last for U.S. Contiguous Customers only.
```

**Comment by Christopher-Hayes** [comment]
Thanks @ckundo that looks perfect. I'm having trouble running `npx @accesslint/auto-vo`, NPM is saying the package is deprecated. https://www.npmjs.com/package/auto-vo

**Comment by ckundo** [comment]
make sure you include the @accesslint/ scope.

**Comment by Christopher-Hayes** [comment]
I did, NPM is erroring that it was not found: https://registry.npmjs.org/@accesslint/auto-vo

![image](https://user-images.githubusercontent.com/6013871/173258218-c2aac32f-4b09-4f90-95d9-6f9cace6f8f2.png)

**Comment by ckundo** [comment]
ah, i published to the GitHub registry thinking it'd propagate... will look into it! in the meantime, what happens if you npm install -g @accesslint/auto-vo and then run auto-vo?

**Comment by Christopher-Hayes** [comment]
The CLI command seems to work fine with just `auto-vo`, so I can use that, thanks.

Edit: Didn't see your previous comment. Trying to install it gets the same error. But, `npx auto-vo` does seem to work.
