### ISSUE TITLE
Question: Can I record VoiceOver as text for comparison?

### ISSUE THREAD

**Issue by tounsoo** [ckundo/auto-vo#27]
Hi, I'm trying to find a tool that I can use with react testing library to create a test for screenreader. I was wondering if VoiceOver can also return the readout as text for comparison.

**Comment by ckundo** [comment]
hi Ben, yes you can initialize the VoiceOver object with logging to stdout with `const voiceOver = new VoiceOver({ log: true });`

**Comment by tounsoo** [comment]
Sorry for the late response @ckundo Thank you! I'll definitely try this out to make my project more accessible :D
